import jax
import jax.numpy as jnp


def partially_refresh_momentum(momentum, rng_key, step_size, L):

    # return momentum

    c1 = jnp.exp(-step_size/L)
    c2 = jnp.sqrt((1-c1**2))
    z = jax.random.normal(rng_key, shape=momentum.shape, dtype=momentum.dtype)
    new_momentum = c1*momentum + c2*z

    return jax.lax.cond(
        jnp.isinf(L),
        lambda _: momentum,
        lambda _: new_momentum,
        operand=None,
    )

# =============================================================================
# 1) GENERAL POISSON BRACKET FUNCTION (scalar)
# =============================================================================
def poisson_bracket_fn(f, g):
    """Compute the Poisson bracket {f, g} for multi-dimensional q and p."""
    df_dq = jax.grad(lambda qr, pr: f(qr, pr), argnums=0)
    df_dp = jax.grad(lambda qr, pr: f(qr, pr), argnums=1)
    dg_dq = jax.grad(lambda qr, pr: g(qr, pr), argnums=0)
    dg_dp = jax.grad(lambda qr, pr: g(qr, pr), argnums=1)

    def poisson_bracket(q, p):
        df_dq_val = df_dq(q, p)
        df_dp_val = df_dp(q, p)
        dg_dq_val = dg_dq(q, p)
        dg_dp_val = dg_dp(q, p)
        
        # For multi-dimensional case, compute dot product of gradients
        return jnp.dot(df_dq_val, dg_dp_val) - jnp.dot(df_dp_val, dg_dq_val)
    
    return poisson_bracket

def make_p_update(V):
    """Create momentum update function for potential V."""
    def p_update(q, p, eps):
        # Assume V returns a scalar
        return p - eps * jax.grad(V)(q)
    return p_update

def make_x_update(T):
    """Create position update function for kinetic energy T."""
    def x_update(q, p, eps):
        # Assume T returns a scalar
        return q + eps * jax.grad(T)(p)
    return x_update

# =============================================================================
# GENERAL LEAPFROG INTEGRATOR FOR SEPARABLE HAMILTONIAN
# =============================================================================
def make_leapfrog_step(T, V, T_next, V_next, lam_fn=None, dot_lam_fn=None):
    """Create a leapfrog step function for separable Hamiltonian with optional weight calculation."""
    p_update = make_p_update(V_next)
    x_update = make_x_update(T_next)
    # T_next = T

    def leapfrog(q, p, eps, t=None):
        
        p_half = p_update(q, p, eps*0.5)
        q_new = x_update(q, p_half, eps)
        p_new = p_update(q_new, p_half, eps*0.5)
        
        # Calculate weight if lambda functions are provided
        
            
        # Energy at old lambda
        H_old = T(p) + V(q)
        # Energy at new lambda (using new positions)
        H_new = T_next(p_new) + V_next(q_new)
        # print("SHAPES", q.shape, q_new.shape, p.shape, p_new.shape)
        # print("Shapes", T(p).shape, T_next(p).shape)
        # jax.debug.print("weights {x}", x=H_new - H_old)
        
        # Log weight change: -(H_new - H_old)
        weight = -(H_new - H_old)
        
        return q_new, p_new, weight
    return leapfrog

def with_maruyama(integrator):
    def maruyama(q, p, eps, L, rng_key, t=None):
        key1, key2 = jax.random.split(rng_key)
        p = partially_refresh_momentum(p, key1, eps/2, L)
        q, p, weight = integrator(q, p, eps, t)
        p = partially_refresh_momentum(p, key2, eps/2, L)
        return q, p, weight
    return maruyama

clip_value = 100.0

def make_cd_euler_step(T, V, A_ansatz, lam, lam_next, dot_lam, dot_lam_next):
    """Create a counterdiabatic Euler step function."""
    dA_dq_scalar = jax.grad(A_ansatz, argnums=0)
    dA_dp_scalar = jax.grad(A_ansatz, argnums=1)
    
    def cd_euler(q, p, eps):
        # Compute gradients of the gauge potential
        dA_dq = dA_dq_scalar(q, p)
        dA_dp = dA_dp_scalar(q, p)
        
        # Clip the gradients to prevent large forces
        dA_dq = jnp.clip(dA_dq, -clip_value, clip_value)
        dA_dp = jnp.clip(dA_dp, -clip_value, clip_value)
        
        # Euler integration for counterdiabatic dynamics
        # dq/dt = dot_lam * dA/dp
        # dp/dt = -dot_lam * dA/dq
        q_new = q + eps * dot_lam * dA_dp
        p_new = p - eps * dot_lam * dA_dq
        
        return q_new, p_new
    return cd_euler 


def compute_counterdiabatic_work(q, p, lam_k, lam_k1, A_ansatz, make_T, make_V):
    """Compute the differential work for counterdiabatic driving.
    
    The work is given by: (-∇ · v_t(X_t) + ∇U_t(X_t) · v_t(X_t) + ∂_t U_t(X_t))
    where v is the flow generated by A as the Hamiltonian and U_t = H.
    """
    # try:
    # For simplicity, we'll compute this term by term
    
    # 1. Compute v = (∂A/∂p, -∂A/∂q) (Hamiltonian vector field generated by A)
    def compute_v(q, p):
        # Compute partial derivatives of A
        dA_dq = jax.grad(A_ansatz, argnums=0)(q, p)
        dA_dp = jax.grad(A_ansatz, argnums=1)(q, p)
        
        # Hamiltonian vector field: v = (∂A/∂p, -∂A/∂q)
        v_q = dA_dp
        v_p = -dA_dq
        
        return v_q, v_p
    
    # 2. Compute ∇ · v (divergence of v)
    def compute_div_v(q, p):
        # ∇ · v = ∂v_q/∂q + ∂v_p/∂p
        v_q, v_p = compute_v(q, p)
        
        # For 1D case, we need to compute ∂v_q/∂q and ∂v_p/∂p
        # ∂v_q/∂q = ∂²A/∂p∂q
        # ∂v_p/∂p = -∂²A/∂q∂p
        # So ∇ · v = ∂²A/∂p∂q - ∂²A/∂q∂p = 0 (by symmetry of mixed partials)
        
        # For numerical stability, we'll compute this explicitly
        # def v_q_fn(qq):
        #     return jax.grad(lambda pp: jnp.squeeze(A_ansatz(qq, pp)), argnums=0)(p)
        
        # def v_p_fn(pp):
        #     return -jax.grad(lambda qq: jnp.squeeze(A_ansatz(qq, pp)), argnums=0)(q)
        
        # div_v_q = jax.grad(v_q_fn, argnums=0)(q)
        # div_v_p = jax.grad(v_p_fn, argnums=0)(p)
        
        # return div_v_q + div_v_p

        return 0
    
    # 3. Compute ∇H · v (gradient of Hamiltonian dotted with v)
    def compute_grad_H_dot_v(q, p, lam):
        T = make_T(lam)
        V = make_V(lam)
        
        # Compute gradient of H = T + V with respect to (q, p)
        def H(qq, pp):
            return T(pp) + V(qq)
        
        grad_H_q = jax.grad(H, argnums=0)(q, p)
        grad_H_p = jax.grad(H, argnums=1)(q, p)
        
        v_q, v_p = compute_v(q, p)
        # jax.debug.print("grad_H_dot_v: {x}", x=(
        #     jax.grad(A_ansatz, argnums=1)(jnp.array([10.0]), jnp.array([10.0])),
        #     jax.grad(A_ansatz, argnums=0)(jnp.array([10.0]), jnp.array([10.0])),

        #     ))
        
        # ∇H · v = ∂H/∂q * v_q + ∂H/∂p * v_p
        return grad_H_q.dot(v_q) + grad_H_p.dot(v_p)
    
  
    H = lambda lam: lambda q, p: make_T(lam)(p) + make_V(lam)(q)
    
    # Define the complete work computation for a single particle
    def compute_work_single(q, p):
        div_v = compute_div_v(q, p)
        grad_H_dot_v = compute_grad_H_dot_v(q, p, lam_k)
        dH_dl = lambda qq, pp: (jax.grad(lambda qqq, ppp, lam: H(lam)(qqq, ppp), argnums=2)(qq, pp, lam_k))

        # jax.debug.print("dH_dl: {x}", x=dH_dl(jnp.array([10.0]), jnp.array([10.0])))
        
        # Combine terms: (-∇ · v + ∇H · v + ∂_t H)
        # work = div_v - jnp.linalg.norm(p) + grad_H_dot_v + dH_dt(q,p)*(lam_k1 - lam_k)
        # work = 0
        # jax.debug.print("grad_H_dot_v: {x}", x=grad_H_dot_v)
        # jax.debug.print("dH_dt: {x}", x=dH_dt(q,p)*(lam_k1 - lam_k))
        # jax.debug.print("terms {x}", x=(grad_H_dot_v, dH_dl(q, p), grad_H_dot_v - dH_dl(q, p)))
        work = grad_H_dot_v + dH_dl(q, p) #  + dH_dt(q,p)*(lam_k1 - lam_k)
        # work = dH_dt(q,p)*(lam_k1 - lam_k)

        
        return -work
    
    # Vectorize over particles
    work_vals = (compute_work_single)(q, p)

    # print("work_vals", work_vals)
    
    return work_vals
        
    # except Exception as e:
    #     # If there's an error, return zeros (no work contribution)
    #     print(f"⚠️  Error computing counterdiabatic work: {e}")
    #     return jnp.zeros_like(q)

def make_cd_leapfrog_step(make_T, make_V, A_ansatz, lam, lam_next, dot_lam, dot_lam_next, lam_fn=None, dot_lam_fn=None):
    T = make_T(lam)
    V = make_V(lam)
    T_next = make_T(lam_next)
    V_next = make_V(lam_next)
    """Create a counterdiabatic leapfrog step function with optional weight calculation.
    
    The full Hamiltonian is H + dot_lam*A where H = T + V.
    Note: Consider updating lambda to lam_next at the midpoint of the step
    for better accuracy, i.e., use (lam + lam_next)/2 and (dot_lam + dot_lam_next)/2.
    """
    dA_dq_scalar = jax.grad(A_ansatz, argnums=0)
    dA_dp_scalar = jax.grad(A_ansatz, argnums=1)
    
    def cd_leapfrog(q, p, eps, t=None):
        # Compute gradients of the gauge potential at initial point
        dA_dq = dA_dq_scalar(q, p)
        dA_dp = dA_dp_scalar(q, p)
        
        # Clip the gradients to prevent large forces
        dA_dq = jnp.clip(dA_dq, -clip_value, clip_value)
        dA_dp = jnp.clip(dA_dp, -clip_value, clip_value)

        # q_new = q + eps * dot_lam * dA_dp
        # p_new = p - eps * dot_lam * dA_dq
        
        log_weight = compute_counterdiabatic_work(q, p, lam, lam_next, A_ansatz, make_T, make_V)*eps*dot_lam

        # q half-step: q_half = q + (eps/2) * (dT/dp + dot_lam * dA/dp)
        q_half = q + 0.5 * eps * (jax.grad(T)(p) + dot_lam * dA_dp)
        # q_half = q + 0.5 * eps * (jax.grad(T)(p))
        
        # p full-step: p_new = p - eps * (dV/dq + dot_lam * dA/dq) at q_half
        dA_dq_half = dA_dq_scalar(q_half, p)
        dA_dq_half = jnp.clip(dA_dq_half, -clip_value, clip_value)
        p_new = p - eps * (jax.grad(V)(q_half) + dot_lam * dA_dq_half)
        # p_new = p - eps * (jax.grad(V)(q_half))
        
        # q half-step: q_new = q_half + (eps/2) * (dT/dp + dot_lam * dA/dp) at p_new
        dA_dp_new = dA_dp_scalar(q_half, p_new)
        dA_dp_new = jnp.clip(dA_dp_new, -clip_value, clip_value)
        q_new = q_half + 0.5 * eps * (jax.grad(T)(p_new) + dot_lam * dA_dp_new)
        # q_new = q_half + 0.5 * eps * (jax.grad(T)(p_new) )
        
        
        
        return q_new, p_new, log_weight
    return cd_leapfrog 
        # # Calculate weight if lambda functions are provided
        # # For counterdiabatic dynamics, weight is computed from the counterdiabatic work
        # # Weight = exp(-W) where W is the integrated work
        # lam_t = lam_fn(t)
        # lam_t_plus_eps = lam_fn(t + eps)
        # dot_lam_t = dot_lam_fn(t)
        
        # # Compute the differential work for counterdiabatic driving
        # # W = ∫ ∂H/∂λ dλ/dt dt ≈ ∂H/∂λ * dλ/dt * eps
        
        # # Calculate ∂H/∂λ = ∂V/∂λ at the midpoint
        # lam_mid = (lam_t + lam_t_plus_eps) / 2.0
        # q_mid = (q + q_new) / 2.0
        
        # # For the double well potential: V(q) = (1-λ)*0.5*q^2 + λ*(((q-2)^2 - 3)^2)
        # # So ∂V/∂λ = -0.5*q^2 + (((q-2)^2 - 3)^2)
        # dV_dlam = -0.5 * jnp.sum(q_mid**2) + jnp.sum(((q_mid - 2)**2 - 3)**2)
        
        # Log weight change: -W where W = ∂H/∂λ * dλ/dt * eps
        # weight = -dV_dlam * dot_lam_t * eps