import jax
import jax.numpy as jnp


def partially_refresh_momentum(momentum, rng_key, step_size, L):

    # return momentum

    c1 = jnp.exp(-step_size/L)
    c2 = jnp.sqrt((1-c1**2))
    z = jax.random.normal(rng_key, shape=momentum.shape, dtype=momentum.dtype)
    new_momentum = c1*momentum + c2*z

    return jax.lax.cond(
        jnp.isinf(L),
        lambda _: momentum,
        lambda _: new_momentum,
        operand=None,
    )

# =============================================================================
# 1) GENERAL POISSON BRACKET FUNCTION (scalar)
# =============================================================================
def poisson_bracket_fn(f, g):
    """Compute the Poisson bracket {f, g} for multi-dimensional q and p."""
    df_dq = jax.grad(lambda qr, pr: f(qr, pr), argnums=0)
    df_dp = jax.grad(lambda qr, pr: f(qr, pr), argnums=1)
    dg_dq = jax.grad(lambda qr, pr: g(qr, pr), argnums=0)
    dg_dp = jax.grad(lambda qr, pr: g(qr, pr), argnums=1)

    def poisson_bracket(q, p):
        df_dq_val = df_dq(q, p)
        df_dp_val = df_dp(q, p)
        dg_dq_val = dg_dq(q, p)
        dg_dp_val = dg_dp(q, p)
        
        # For multi-dimensional case, compute dot product of gradients
        return jnp.dot(df_dq_val, dg_dp_val) - jnp.dot(df_dp_val, dg_dq_val)
    
    return poisson_bracket

def make_p_update(V):
    """Create momentum update function for potential V."""
    def p_update(q, p, eps):
        # Assume V returns a scalar
        return p - eps * jax.grad(V)(q)
    return p_update

def make_x_update(T):
    """Create position update function for kinetic energy T."""
    def x_update(q, p, eps):
        # Assume T returns a scalar
        return q + eps * jax.grad(T)(p)
    return x_update

# =============================================================================
# GENERAL LEAPFROG INTEGRATOR FOR SEPARABLE HAMILTONIAN
# =============================================================================

def leapfrog(O1, O2, eps, q, p):
    p_half = O1(q, p, eps*0.5)
    q_new = O2(q, p_half, eps)
    p_new = O1(q_new, p_half, eps*0.5)
    return q_new, p_new


def make_leapfrog_step(T, V, T_next, V_next, lam_fn=None, dot_lam_fn=None):
    """Create a leapfrog step function for separable Hamiltonian with optional weight calculation."""
    p_update = make_p_update(V_next)
    x_update = make_x_update(T_next)
    # T_next = T

    def step(q, p, eps):

        q_new, p_new = leapfrog(p_update, x_update, eps, q, p)
        H_old = T(p) + V(q)
        H_new = T_next(p_new) + V_next(q_new)
        
        weight = -(H_new - H_old)
        
        return q_new, p_new, weight
    return step

def with_maruyama(integrator):
    def maruyama(q, p, eps, L, rng_key):
        key1, key2 = jax.random.split(rng_key)
        p = partially_refresh_momentum(p, key1, eps/2, L)
        q, p, weight = integrator(q, p, eps)
        p = partially_refresh_momentum(p, key2, eps/2, L)
        return q, p, weight
    return maruyama

clip_value = jnp.inf

def make_cd_euler_step(T, V, A_ansatz, lam, lam_next, dot_lam, dot_lam_next):
    """Create a counterdiabatic Euler step function."""
    dA_dq_scalar = jax.grad(A_ansatz, argnums=0)
    dA_dp_scalar = jax.grad(A_ansatz, argnums=1)
    
    def cd_euler(q, p, eps):
        # Compute gradients of the gauge potential
        dA_dq = dA_dq_scalar(q, p)
        dA_dp = dA_dp_scalar(q, p)
        
        # Clip the gradients to prevent large forces
        dA_dq = jnp.clip(dA_dq, -clip_value, clip_value)
        dA_dp = jnp.clip(dA_dp, -clip_value, clip_value)
        
        # Euler integration for counterdiabatic dynamics
        # dq/dt = dot_lam * dA/dp
        # dp/dt = -dot_lam * dA/dq
        q_new = q + eps * dot_lam * dA_dp
        p_new = p - eps * dot_lam * dA_dq
        
        return q_new, p_new
    return cd_euler 


def compute_counterdiabatic_work(q, p, q_new, p_new, lam_k, lam_k1, A_ansatz, make_T, make_V):
    """Compute the differential work for counterdiabatic driving.
    
    The work is given by: (-∇ · v_t(X_t) + ∇U_t(X_t) · v_t(X_t) + ∂_t U_t(X_t))
    where v is the flow generated by A as the Hamiltonian and U_t = H.
    """
   
    def compute_v(q, p):
        # Compute partial derivatives of A
        dA_dq = jax.grad(A_ansatz, argnums=0)(q, p)
        dA_dp = jax.grad(A_ansatz, argnums=1)(q, p)
        
        # Hamiltonian vector field: v = (∂A/∂p, -∂A/∂q)
        v_q = dA_dp
        v_p = -dA_dq
        
        return v_q, v_p
    
    # 2. Compute ∇ · v (divergence of v)
    def compute_div_v(q, p):
        # ∇ · v = ∂v_q/∂q + ∂v_p/∂p
        v_q, v_p = compute_v(q, p)
        
        # For 1D case, we need to compute ∂v_q/∂q and ∂v_p/∂p
        # ∂v_q/∂q = ∂²A/∂p∂q
        # ∂v_p/∂p = -∂²A/∂q∂p
        # So ∇ · v = ∂²A/∂p∂q - ∂²A/∂q∂p = 0 (by symmetry of mixed partials)
        
        # For numerical stability, we'll compute this explicitly
        # def v_q_fn(qq):
        #     return jax.grad(lambda pp: jnp.squeeze(A_ansatz(qq, pp)), argnums=0)(p)
        
        # def v_p_fn(pp):
        #     return -jax.grad(lambda qq: jnp.squeeze(A_ansatz(qq, pp)), argnums=0)(q)
        
        # div_v_q = jax.grad(v_q_fn, argnums=0)(q)
        # div_v_p = jax.grad(v_p_fn, argnums=0)(p)
        
        # return div_v_q + div_v_p

        return 0
    
    # 3. Compute ∇H · v (gradient of Hamiltonian dotted with v)
    def compute_grad_H_dot_v(q, p, lam):
        T = make_T(lam)
        V = make_V(lam)
        
        # Compute gradient of H = T + V with respect to (q, p)
        def H(qq, pp):
            return T(pp) + V(qq)
        
        grad_H_q = jax.grad(H, argnums=0)(q, p)
        grad_H_p = jax.grad(H, argnums=1)(q, p)
        
        v_q, v_p = compute_v(q, p)
        return grad_H_q.dot(v_q) + grad_H_p.dot(v_p)
    
  
    H = lambda lam: lambda q, p: make_T(lam)(p) + make_V(lam)(q)
    delta_H = H(lam_k1)(q_new, p_new) - H(lam_k)(q, p)
    
    # Define the complete work computation for a single particle
    # def compute_work_single(q, p):
    #     div_v = compute_div_v(q, p)
    #     grad_H_dot_v = compute_grad_H_dot_v(q, p, lam_k)
    #     dH_dl = lambda qq, pp: (jax.grad(lambda qqq, ppp, lam: H(lam)(qqq, ppp), argnums=2)(qq, pp, lam_k))
    #     work = grad_H_dot_v + dH_dl(q, p)

    #     return -work

    
    return -delta_H

def make_cd_leapfrog_step(make_T, make_V, A_ansatz, lam, lam_next, dot_lam, dot_lam_next, lam_fn=None, dot_lam_fn=None):
    T = make_T(lam)
    V = make_V(lam)
    T_next = make_T(lam_next)
    V_next = make_V(lam_next)
    """Create a counterdiabatic leapfrog step function with optional weight calculation.
    
    The full Hamiltonian is H + dot_lam*A where H = T + V.
    Note: Consider updating lambda to lam_next at the midpoint of the step
    for better accuracy, i.e., use (lam + lam_next)/2 and (dot_lam + dot_lam_next)/2.
    """
    dA_dq_scalar = jax.jacobian(A_ansatz, argnums=0)
    dA_dp_scalar = jax.jacobian(A_ansatz, argnums=1)
    
    def cd_leapfrog(q, p, eps):
        
        
        
        q, p = leapfrog(make_p_update(make_V(lam)), make_x_update(make_T(lam)), eps/2, q, p)
        # return q, p, 0

        print("dot lam shape", dot_lam.shape)
        

        q_half = q + 0.5 * eps * (dot_lam.dot(jnp.clip(dA_dp_scalar(q, p), -clip_value, clip_value)))
        p_new = p - eps * (dot_lam.dot(jnp.clip(dA_dq_scalar(q_half, p), -clip_value, clip_value)))
        q_new = q_half + 0.5 * eps * (dot_lam.dot(jnp.clip(dA_dp_scalar(q_half, p_new), -clip_value, clip_value)))

        q_new, p_new = leapfrog(make_p_update(make_V(lam_next)), make_x_update(make_T(lam_next)), eps/2, q_new, p_new)
        
        log_weight = compute_counterdiabatic_work(q, p, q_new, p_new, lam, lam_next, A_ansatz, make_T, make_V)

        return q_new, p_new, log_weight
    return cd_leapfrog 
       
#=============================================================================
# IMPLICIT MIDPOINT INTEGRATOR
# =============================================================================

def newton_solve(f, x0, max_iter=10, tol=1e-8):
    """
    Solve f(x) = 0 using Newton's method.
    
    Args:
        f: Function that returns (residual, jacobian) given x
        x0: Initial guess
        max_iter: Maximum number of iterations
        tol: Convergence tolerance
    
    Returns:
        Solution x such that f(x) ≈ 0
    """
    def newton_step(x):
        residual, jacobian = f(x)
        # Solve J * dx = -r for dx
        dx = jnp.linalg.solve(jacobian, -residual)
        return x + dx
    
    def newton_iteration(x, i):
        new_x = newton_step(x)
        residual, _ = f(new_x)
        converged = jnp.linalg.norm(residual) < tol
        return new_x, converged
    
    # Use JAX scan for efficient iteration
    x_final, converged = jax.lax.scan(
        lambda x, _: newton_iteration(x, 0),
        x0,
        jnp.arange(max_iter)
    )
    
    return x_final

def make_implicit_midpoint_step(H):
    """
    Create an implicit midpoint integrator step function.
    
    The integrator is a composition of two half-steps:
    1. Implicit Euler: z^(n+1/2) = z^n + (1/2) * Δt * J * ∇H(z^(n+1/2))
    2. Explicit Euler: z^(n+1) = z^(n+1/2) + (1/2) * Δt * J * ∇H(z^(n+1/2))
    
    Args:
        H: Hamiltonian function H(q, p) - need not be separable
    
    Returns:
        Function that takes (q, p, dt) and returns (q_new, p_new, weight)
    """
    
    def implicit_midpoint_step(q, p, dt):
        """
        Single step of implicit midpoint integrator.
        
        Args:
            q: Position vector
            p: Momentum vector  
            dt: Time step
        
        Returns:
            (q_new, p_new, weight) where weight is the energy change
        """
        # Combine position and momentum into single state vector
        z = jnp.concatenate([q, p])
        
        # Define the symplectic matrix J
        n = len(q)
        J = jnp.block([[jnp.zeros((n, n)), jnp.eye(n)],
                       [-jnp.eye(n), jnp.zeros((n, n))]])
        
        # Define gradient of Hamiltonian
        def grad_H(q, p):
            grad_q = jax.grad(H, argnums=0)(q, p)
            grad_p = jax.grad(H, argnums=1)(q, p)
            return jnp.concatenate([grad_q, grad_p])
        
        # Define the implicit equation for the first half-step
        # z^(n+1/2) = z^n + (1/2) * dt * J * ∇H(z^(n+1/2))
        def implicit_equation(z_half):
            q_half, p_half = z_half[:n], z_half[n:]
            grad_H_half = grad_H(q_half, p_half)
            residual = z_half - z - 0.5 * dt * J @ grad_H_half
            return residual
        
        # Define function for Newton solver (residual, jacobian)
        def newton_function(z_half):
            residual = implicit_equation(z_half)
            jacobian = jax.jacobian(implicit_equation)(z_half)
            return residual, jacobian
        
        # Solve the implicit equation for z^(n+1/2)
        z_half = newton_solve(newton_function, z)
        q_half, p_half = z_half[:n], z_half[n:]
        
        # Second half-step: explicit Euler
        # z^(n+1) = z^(n+1/2) + (1/2) * dt * J * ∇H(z^(n+1/2))
        grad_H_half = grad_H(q_half, p_half)
        z_new = z_half + 0.5 * dt * J @ grad_H_half
        
        q_new, p_new = z_new[:n], z_new[n:]
        
        # Calculate energy change for weight
        H_old = H(q, p)
        H_new = H(q_new, p_new)
        weight = -(H_new - H_old)
        
        return q_new, p_new, weight
    
    return implicit_midpoint_step

def make_cd_implicit_midpoint_step(make_T, make_V, A_ansatz, lam, lam_next, dot_lam, dot_lam_next):
    """
    Create a counterdiabatic implicit midpoint step function.
    
    The full Hamiltonian is H + dot_lam*A where H = T + V.
    This uses the implicit midpoint integrator for the combined Hamiltonian.
    
    Args:
        make_T: Function to create kinetic energy T(lam)
        make_V: Function to create potential energy V(lam)
        A_ansatz: Gauge potential ansatz
        lam: Current lambda value
        lam_next: Next lambda value
        dot_lam: Current lambda derivative
        dot_lam_next: Next lambda derivative
    
    Returns:
        Function that takes (q, p, eps, t) and returns (q_new, p_new, weight)
    """
    
    def cd_implicit_midpoint_step(q, p, eps, t=None):
        """
        Single step of counterdiabatic implicit midpoint integrator.
        
        Args:
            q: Position vector
            p: Momentum vector
            eps: Time step
            t: Time (optional, for compatibility)
        
        Returns:
            (q_new, p_new, weight) where weight is the energy change
        """
        # Define the full Hamiltonian H + dot_lam*A
        def H_full(q, p):
            T = make_T(lam)
            V = make_V(lam)
            # return T(p) + V(q) + dot_lam * A_ansatz(q, p)
            return dot_lam * A_ansatz(q, p)
        
        # Create the implicit midpoint integrator for the full Hamiltonian
        implicit_midpoint = make_implicit_midpoint_step(H_full)
        
        # Take one step
        q_new, p_new, weight = implicit_midpoint(q, p, eps)
        
        # Compute counterdiabatic work for weight calculation
        # The weight from implicit midpoint is the energy change of H_full
        # We want the counterdiabatic work, which is the change in the original Hamiltonian H
        T_old = make_T(lam)
        V_old = make_V(lam)
        T_new = make_T(lam_next)
        V_new = make_V(lam_next)
        
        H_old = T_old(p) + V_old(q)
        H_new = T_new(p_new) + V_new(q_new)
        
        # Counterdiabatic work is the change in the original Hamiltonian
        cd_work = H_new - H_old
        
        return q_new, p_new, -cd_work
    
    return cd_implicit_midpoint_step