import jax
import jax.numpy as jnp
import numpy as np
import equinox as eqx

from .physics import make_cd_leapfrog_step, make_leapfrog_step, make_cd_euler_step, partially_refresh_momentum, with_maruyama
from .fitting import fit_gauge_potential
from .ansatze import AnalyticAnsatz, PolynomialAnsatz, NeuralNetworkAnsatz

def check_nans(name, value, step=None):
    """Helper function to check for NaNs and print warnings."""
    # Convert to numpy for checking to avoid JAX tracing issues
    if hasattr(value, 'numpy'):
        value_np = value.numpy()
    else:
        value_np = value
    
    if jnp.isnan(value_np).any():
        count = jnp.isnan(value_np).sum()
        step_info = f" at step {step}" if step is not None else ""
        print(f"⚠️  NaN detected in {name}{step_info} (count: {count})")
        return True
    return False

def compute_ess(log_weights):
    """Compute effective sample size from log weights using the formula:
    ESS = (Σ_{n=1}^{N} w_t(x_{t-1}^n))^2 / Σ_{n=1}^{N} w_t(x_{t-1}^n)^2
    """
    # Convert log weights to regular weights
    weights = jnp.exp(log_weights - jnp.max(log_weights))  # Numerical stability
    
    # Compute the formula: (sum of weights)^2 / sum of squared weights
    sum_weights = jnp.sum(weights)
    sum_squared_weights = jnp.sum(weights ** 2)
    
    # ESS = (sum_weights)^2 / sum_squared_weights
    ess = (sum_weights ** 2) / sum_squared_weights
    
    return ess

def multinomial_resample(q, p, log_weights, rng_key, M):
    """Perform multinomial resampling and reset weights to uniform."""
    weights = jnp.exp(log_weights - jnp.max(log_weights))  # Numerical stability
    weights = weights / jnp.sum(weights)  # Normalize
    
    # Generate multinomial samples
    indices = jax.random.choice(rng_key, M, shape=(M,), p=weights, replace=True)
    
    # Resample particles
    q_resampled = q[indices]
    p_resampled = p[indices]
    
    # Reset weights to uniform (log weights = 0)
    log_weights_reset = jnp.zeros(M)
    
    return q_resampled, p_resampled, log_weights_reset

def compute_energy_stats(q, p, lam, make_T, make_V):
    """Compute average H, H², ∂H/∂λ, and (∂H/∂λ)² over particles."""
    T = make_T(lam)
    V = make_V(lam)
    
    # Compute H for each particle
    H_vals = jax.vmap(lambda qr, pr: T(pr) + V(qr))(q, p)
    
    # Compute ∂H/∂λ for each particle
    dH_dlam = lambda q, p: (jax.grad(lambda q, p, lam: make_V(lam)(q), argnums=2)(q, p, lam))
    
    dH_dlam_vals = jax.vmap(lambda qr, pr: dH_dlam(qr, pr))(q, p)
    
    # Compute averages
    avg_H = jnp.mean(H_vals)
    avg_H_sq = jnp.mean(H_vals ** 2)
    avg_dH_dlam = jnp.mean(dH_dlam_vals)
    avg_dH_dlam_sq = jnp.mean(dH_dlam_vals ** 2)
    
    return {
        'avg_H': float(avg_H),
        'avg_H_sq': float(avg_H_sq),
        'avg_dH_dlam': float(avg_dH_dlam),
        'avg_dH_dlam_sq': float(avg_dH_dlam_sq),
        'H_vals': H_vals  # Store individual H values
    }

def compute_naive_weights(q, p, lam_k, lam_k1, make_T, make_V):
    """Compute importance weights for naive HMC based on energy difference."""
    # Compute energy at old and new lambda values for each particle
    T_old = make_T(lam_k)
    V_old = make_V(lam_k)
    T_new = make_T(lam_k1)
    V_new = make_V(lam_k1)
    
    # Compute energies for each particle
    def compute_energy(q, p, T_fn, V_fn):
        return T_fn(p) + V_fn(q)
    
    # Vectorize over particles
    energy_old = jax.vmap(lambda q, p: compute_energy(q, p, T_old, V_old))(q, p)
    energy_new = jax.vmap(lambda q, p: compute_energy(q, p, T_new, V_new))(q, p)

    # H = lambda lam: lambda q, p: make_T(lam)(p) + make_V(lam)(q)
    # dH_dt = lambda qq, pp: (jax.grad(lambda q, p, lam: H(lam)(q, p), argnums=2)(qq, pp, lam_k))
    
    # Log weight update: log(w_new) = log(w_old) - (H_new - H_old)
    # This is the negative change in energy (Boltzmann factor)

    direct = (energy_new - energy_old)
    # indirect = jax.vmap(lambda q, p: dH_dt(q,p)*(lam_k1 - lam_k))(q,p)
    # print("fpp", direct, indirect, np.abs(direct - indirect))
    log_weight_update = -(energy_new - energy_old)
    # log_weight_update = -indirect
    
    return log_weight_update

def compute_counterdiabatic_work(q, p, lam_k, lam_k1, A_ansatz, make_T, make_V):
    """Compute the differential work for counterdiabatic driving.
    
    The work is given by: (-∇ · v_t(X_t) + ∇U_t(X_t) · v_t(X_t) + ∂_t U_t(X_t))
    where v is the flow generated by A as the Hamiltonian and U_t = H.
    """
    # try:
    # For simplicity, we'll compute this term by term
    
    # 1. Compute v = (∂A/∂p, -∂A/∂q) (Hamiltonian vector field generated by A)
    def compute_v(q, p):
        # Compute partial derivatives of A
        dA_dq = jax.grad(A_ansatz, argnums=0)(q, p)
        dA_dp = jax.grad(A_ansatz, argnums=1)(q, p)
        
        # Hamiltonian vector field: v = (∂A/∂p, -∂A/∂q)
        v_q = dA_dp
        v_p = -dA_dq
        
        return v_q, v_p
    
    # 2. Compute ∇ · v (divergence of v)
    def compute_div_v(q, p):
        # ∇ · v = ∂v_q/∂q + ∂v_p/∂p
        v_q, v_p = compute_v(q, p)
        
        # For 1D case, we need to compute ∂v_q/∂q and ∂v_p/∂p
        # ∂v_q/∂q = ∂²A/∂p∂q
        # ∂v_p/∂p = -∂²A/∂q∂p
        # So ∇ · v = ∂²A/∂p∂q - ∂²A/∂q∂p = 0 (by symmetry of mixed partials)
        
        # For numerical stability, we'll compute this explicitly
        # def v_q_fn(qq):
        #     return jax.grad(lambda pp: jnp.squeeze(A_ansatz(qq, pp)), argnums=0)(p)
        
        # def v_p_fn(pp):
        #     return -jax.grad(lambda qq: jnp.squeeze(A_ansatz(qq, pp)), argnums=0)(q)
        
        # div_v_q = jax.grad(v_q_fn, argnums=0)(q)
        # div_v_p = jax.grad(v_p_fn, argnums=0)(p)
        
        # return div_v_q + div_v_p

        return 0
    
    # 3. Compute ∇H · v (gradient of Hamiltonian dotted with v)
    def compute_grad_H_dot_v(q, p, lam):
        T = make_T(lam)
        V = make_V(lam)
        
        # Compute gradient of H = T + V with respect to (q, p)
        def H(qq, pp):
            return T(pp) + V(qq)
        
        grad_H_q = jax.grad(H, argnums=0)(q, p)
        grad_H_p = jax.grad(H, argnums=1)(q, p)
        
        v_q, v_p = compute_v(q, p)
        
        # ∇H · v = ∂H/∂q * v_q + ∂H/∂p * v_p
        return grad_H_q.dot(v_q) + grad_H_p.dot(v_p)
    
  
    H = lambda lam: lambda q, p: make_T(lam)(p) + make_V(lam)(q)
    
    # Define the complete work computation for a single particle
    def compute_work_single(q, p):
        div_v = compute_div_v(q, p)
        grad_H_dot_v = compute_grad_H_dot_v(q, p, lam_k)
        dH_dt = lambda qq, pp: (jax.grad(lambda qqq, ppp, lam: H(lam)(qqq, ppp), argnums=2)(qq, pp, lam_k))

        
        # Combine terms: (-∇ · v + ∇H · v + ∂_t H)
        # work = div_v - jnp.linalg.norm(p) + grad_H_dot_v + dH_dt(q,p)*(lam_k1 - lam_k)
        # work = 0
        # jax.debug.print("grad_H_dot_v: {x}", x=grad_H_dot_v)
        # jax.debug.print("dH_dt: {x}", x=dH_dt(q,p)*(lam_k1 - lam_k))
        work = grad_H_dot_v + dH_dt(q,p)*(lam_k1 - lam_k)
        # work = dH_dt(q,p)*(lam_k1 - lam_k)

        
        return work
    
    # Vectorize over particles
    work_vals = jax.vmap(compute_work_single)(q, p)

    # print("work_vals", work_vals)
    
    return work_vals
        
    # except Exception as e:
    #     # If there's an error, return zeros (no work contribution)
    #     print(f"⚠️  Error computing counterdiabatic work: {e}")
    #     return jnp.zeros_like(q)

def record_snapshots(snapshots, k, q_naive, q_cd, lam_k, use_weights, log_weights_naive, log_weights_cd, 
                    resampling_count_naive, resampling_count_cd, param_history, A_ansatz):
    """Record snapshots and parameters every 10 steps."""
    if k % 10 == 0:
        snapshots['naive'].append(np.array(q_naive))
        # Always store weighted samples (weights are always computed)
        snapshots['naive_weighted'].append(np.array(q_naive))
        snapshots['weights_naive'].append(np.array(log_weights_naive))
        snapshots['resampling_events_naive'].append(resampling_count_naive)
        
        # Store weighted samples for CD-HMC
        snapshots['cd_weighted'].append(np.array(q_cd))
        snapshots['weights_cd'].append(np.array(log_weights_cd))
        snapshots['resampling_events_cd'].append(resampling_count_cd)
        
        snapshots['cd_pre_equil'].append(np.array(q_cd)) # Store pre-equilibration state
        snapshots['lam_pre_equil'].append(lam_k) # Store lambda at pre-equilibration
        
        # Record parameters
        if isinstance(A_ansatz, PolynomialAnsatz):
            param_history.append(np.array(A_ansatz.params))
            # Check parameters for NaNs
            check_nans("polynomial_params", A_ansatz.params, k)
        elif isinstance(A_ansatz, NeuralNetworkAnsatz):
            # Store just the parameters as a tuple of arrays
            params = []
            for layer in A_ansatz.layers:
                if isinstance(layer, eqx.nn.Linear):
                    params.append(np.array(layer.weight))
                    params.append(np.array(layer.bias))
            param_history.append(tuple(params))
        elif isinstance(A_ansatz, AnalyticAnsatz):
            param_history.append(np.array(A_ansatz.params))
            check_nans("analytic_params", A_ansatz.params, k)

# =============================================================================
# 6) SImuLATION: NAÏVE HMC VS CD WITH ONLINE FITTING
# =============================================================================
def generate_initial_samples(M, make_T, make_V, lam, key, dim, num_steps=1000, eps=0.05, L=4.0):
    """Generate M samples from the distribution at the given temperature using HMC.
    
    Args:
        M: Number of samples
        make_T: Function to create kinetic energy
        make_V: Function to create potential energy
        lam: Current lambda value
        key: JAX random key
        dim: Dimension of the system
        num_steps: Number of HMC steps for equilibration
        eps: Step size for HMC
    """
    # Start from random positions
    key, sub = jax.random.split(key)
    q = jax.random.normal(sub, (M, dim))
    key, sub = jax.random.split(key)
    p = jax.random.normal(sub, (M, dim)) 
    

    # Check initial samples for NaNs
    check_nans("initial_q", q)
    check_nans("initial_p", p)

    # Run HMC for a while to get to equilibrium
    T = make_T(lam)
    V = make_V(lam)
    step = jax.jit(with_maruyama(make_leapfrog_step(T, V)))
    
    # qs = []
    # ps = []
    for step_idx in range(num_steps):
        key, sub = jax.random.split(key)
        subs = jax.random.split(sub, M)
        q, p = jax.vmap(lambda q, p, k: step(q, p, eps, L=L, rng_key=k))(q, p, subs)
        
        # Check for NaNs during equilibration
        if check_nans("equilibration_q", q, step_idx):
            print(f"  Stopping equilibration early due to NaNs at step {step_idx}")
            break
        if check_nans("equilibration_p", p, step_idx):
            print(f"  Stopping equilibration early due to NaNs at step {step_idx}")
            break

        # qs.append(np.array(q))
        # ps.append(np.array(p))
        # Randomize momenta periodically
        # if step_idx % 20 == 0:
        #     key, sub = jax.random.split(key)
        #     p = jax.random.normal(sub, (M, dim))
    
    # return np.array(qs), np.array(ps)
    return q, p

def run_naive_hmc_simulation(M, N_steps, delta_t, eps, momentum_refresh_interval, make_T, make_V, lam_fn, dot_lam_fn, key, dim, use_weights=False, ess_threshold=0.5):
    """Run naive HMC simulation without fitting the ansatz (for efficiency)."""
    
    # Generate initial samples from the correct distribution
    initial_lam = float(lam_fn(0.0))
    print(f"Generating initial samples with λ = {initial_lam}")
    q_naive, p_naive = generate_initial_samples(M, make_T, make_V, initial_lam, key, dim)

    # Check initial samples
    check_nans("initial_q_naive", q_naive)
    check_nans("initial_p_naive", p_naive)

    # Initialize weights for SMC (Sequential Monte Carlo) - always use weights
    log_weights = jnp.zeros(M)  # Initial weights are uniform (log weights = 0)
    if use_weights:
        print("Using Sequential Monte Carlo with importance weights")
    else:
        print("Using Sequential Monte Carlo with unit weights (no resampling)")

    snapshots = {'naive': [], 'naive_weighted': [], 'lam_pre_equil': [], 'weights_naive': [], 'resampling_events_naive': []}
    resampling_count = 0  # Track number of resampling events

    for k in range(N_steps + 1):
        t_k = k * delta_t
        lam_k = float(lam_fn(t_k))
        dot_lam_k = float(dot_lam_fn(t_k))

        # Check lambda values for NaNs
        if jnp.isnan(lam_k):
            print(f"⚠️  NaN detected in lam_k at step {k}")
            break
        if jnp.isnan(dot_lam_k):
            print(f"⚠️  NaN detected in dot_lam_k at step {k}")
            break

        # Record snapshots every 10 steps
        if k % 10 == 0:
            snapshots['naive'].append(np.array(q_naive))
            snapshots['naive_weighted'].append(np.array(q_naive))
            snapshots['weights_naive'].append(np.array(log_weights))
            snapshots['resampling_events_naive'].append(resampling_count)
            snapshots['lam_pre_equil'].append(lam_k)

        if k == N_steps:
            break

        lam_k1 = float(lam_fn(t_k + delta_t))
        dot_lam_k1 = float(dot_lam_fn(t_k + delta_t))

        # Check next lambda values for NaNs
        if jnp.isnan(lam_k1):
            print(f"⚠️  NaN detected in lam_k1 at step {k}")
            break
        if jnp.isnan(dot_lam_k1):
            print(f"⚠️  NaN detected in dot_lam_k1 at step {k}")
            break

        key, sub = jax.random.split(key)
        subs = jax.random.split(sub, M)
        naive_step = jax.vmap(lambda q, p, lam, lam_next, eps, L, rng_key: with_maruyama(make_leapfrog_step(make_T(lam), make_V(lam)))(q,p,eps,L=L, rng_key=rng_key), in_axes=(0, 0, None, None, None, None, 0))

        # --- Naïve step ---
        q_naive, p_naive = jax.jit(naive_step)(q_naive, p_naive, lam_k, lam_k1, eps, eps*momentum_refresh_interval, subs)

        # Check for NaNs in naive HMC
        if check_nans("q_naive", q_naive, k):
            print(f"  Stopping simulation due to NaNs in naive HMC at step {k}")
            break
        if check_nans("p_naive", p_naive, k):
            print(f"  Stopping simulation due to NaNs in naive HMC at step {k}")
            break

        # --- Compute importance weights for SMC ---
        
        if use_weights:
            # Apply weight update
            log_weight_update = compute_naive_weights(q_naive, p_naive, lam_k, lam_k1, make_T, make_V)
            log_weights = log_weights + log_weight_update
            
            # Check for NaNs in weights
            if check_nans("log_weights", log_weights, k):
                print(f"  Stopping simulation due to NaNs in weights at step {k}")
                break
            
            # Check if resampling is needed
            ess = compute_ess(log_weights)
            ess_ratio = ess / M
            
            if ess_ratio < ess_threshold:
                print(f"  Resampling at step {k}: ESS = {ess:.1f}/{M} ({ess_ratio:.3f})")
                key, sub = jax.random.split(key)
                q_naive, p_naive, log_weights = multinomial_resample(q_naive, p_naive, log_weights, sub, M)
                resampling_count += 1
                print(f"    Resampling completed. Total resampling events: {resampling_count}")
        else:
            # Keep weights at 1 (log_weights = 0) when not using weights
            log_weights = jnp.zeros(M)

    print(f"Simulat(energy_new - energy_old)ion completed after {k} steps")
    if use_weights:
        print(f"Total resampling events: {resampling_count}")
    
    return snapshots

def run_simulation(M, N_steps, delta_t, eps, momentum_refresh_interval, fit_every, num_initial_iterations, num_iterations, make_T, make_V, A_ansatz, lam_fn, dot_lam_fn, key, dim, learning_rate=1e-4, re_equil_steps=0, use_weights=False, ess_threshold=0.5):
    
    # Generate initial samples from the correct distribution
    initial_lam = float(lam_fn(0.0))
    print(f"Generating initial samples with λ = {initial_lam}")
    q_naive, p_naive = generate_initial_samples(M, make_T, make_V, initial_lam, key, dim)
    q_cd = q_naive.copy()
    p_cd = p_naive.copy()

    # Check initial samples
    check_nans("initial_q_naive", q_naive)
    check_nans("initial_p_naive", p_naive)
    check_nans("initial_q_cd", q_cd)
    check_nans("initial_p_cd", p_cd)

    # Initialize weights for SMC (Sequential Monte Carlo) - always use weights
    log_weights_naive = jnp.zeros(M)  # Initial weights are uniform (log weights = 0)
    log_weights_cd = jnp.zeros(M)     # Initial weights for CD-HMC
    if use_weights:
        print("Using Sequential Monte Carlo with importance weights")
    else:
        print("Using Sequential Monte Carlo with unit weights (no resampling)")

    loss_histories = []
    snapshots = {'naive': [], 'naive_weighted': [], 'cd_pre_equil': [], 'cd_post_equil': [], 'cd_weighted': [], 'lam_pre_equil': [], 'lam_post_equil': [], 'energy_stats': [], 'weights_naive': [], 'weights_cd': [], 'resampling_events_naive': [], 'resampling_events_cd': []}
    param_history = []  # Track parameter history
    first_fit = True
    resampling_count_naive = 0  # Track number of resampling events for naive
    resampling_count_cd = 0     # Track number of resampling events for CD



    # Store previous energy values for computing changes
    prev_naive_H_vals = None
    prev_cd_H_vals = None
    
    # Arrays to store energy statistics at every timestep
    all_energy_stats = []
    all_times = []

    for k in range(N_steps + 1):
        t_k = k * delta_t
        lam_k = float(lam_fn(t_k))
        dot_lam_k = float(dot_lam_fn(t_k))

        # Check lambda values for NaNs
        if jnp.isnan(lam_k):
            print(f"⚠️  NaN detected in lam_k at step {k}")
            break
        if jnp.isnan(dot_lam_k):
            print(f"⚠️  NaN detected in dot_lam_k at step {k}")
            break

        # Update lambda parameter for analytic ansatz
        if isinstance(A_ansatz, AnalyticAnsatz):
            A_ansatz = eqx.tree_at(lambda m: m.params, A_ansatz, jnp.array([lam_k]))

        # Re-fit A every fit_every steps
        if not isinstance(A_ansatz, AnalyticAnsatz) and (k % fit_every == 0) and (k < N_steps):
            print(f"Fitting ansatz at step {k} with λ = {lam_k}")
            
            # Check samples before fitting
            check_nans("fitting_samples_q", q_cd, k)
            check_nans("fitting_samples_p", p_cd, k)
            
            # For multi-dimensional case, stack q and p along the last axis
            samples = np.concatenate([np.array(q_cd), np.array(p_cd)], axis=1)
            
            # Use different number of iterations for first vs subsequent fittings
            if first_fit:
                num_iters = num_initial_iterations
                first_fit = False
            else:
                num_iters = num_iterations
                
            # Warm start: use current ansatz parameters as initialization
            # Convert log weights to regular weights if using weights
            weights = None
            if use_weights:
                weights = jnp.exp(log_weights_cd - jnp.max(log_weights_cd))  # Numerical stability
                weights = weights / jnp.sum(weights)  # Normalize
            
            A_ansatz, loss_history = fit_gauge_potential(lam_k, samples,
                                        make_T=make_T, make_V=make_V,
                                        A_ansatz=A_ansatz,  # Pass current ansatz for warm start
                                        num_iters=num_iters, lr=learning_rate,
                                        use_regularization=False, weights=weights)
            
            # Check loss history for NaNs
            if any(jnp.isnan(loss) for loss in loss_history):
                print(f"⚠️  NaN detected in loss history at step {k}")
                nan_indices = [i for i, loss in enumerate(loss_history) if jnp.isnan(loss)]
                print(f"  NaN losses at iterations: {nan_indices}")
            
            loss_histories.append(loss_history)

        # Compute energy statistics at every timestep
        naive_stats = compute_energy_stats(q_naive, p_naive, lam_k, make_T, make_V)
        cd_stats = compute_energy_stats(q_cd, p_cd, lam_k, make_T, make_V)
        
        # Compute energy changes if we have previous values
        if prev_naive_H_vals is not None and prev_cd_H_vals is not None:
            # Compute individual particle energy changes
            naive_delta_H_vals = naive_stats['H_vals'] - prev_naive_H_vals
            cd_delta_H_vals = cd_stats['H_vals'] - prev_cd_H_vals
            
            # Average the individual changes
            naive_avg_delta_H = jnp.mean(naive_delta_H_vals)
            cd_avg_delta_H = jnp.mean(cd_delta_H_vals)
            
            # Add change statistics to the stats dictionaries
            naive_stats['avg_delta_H'] = float(naive_avg_delta_H)
            naive_stats['avg_delta_H_sq'] = float(jnp.mean(naive_delta_H_vals ** 2))
            cd_stats['avg_delta_H'] = float(cd_avg_delta_H)
            cd_stats['avg_delta_H_sq'] = float(jnp.mean(cd_delta_H_vals ** 2))
        else:
            # First timestep - no change to compute
            naive_stats['avg_delta_H'] = 0.0
            naive_stats['avg_delta_H_sq'] = 0.0
            cd_stats['avg_delta_H'] = 0.0
            cd_stats['avg_delta_H_sq'] = 0.0
        
        # Store energy statistics for this timestep
        all_energy_stats.append({
            'naive': naive_stats,
            'cd': cd_stats
        })
        all_times.append(t_k)
        
        # Update previous energy values for next iteration
        prev_naive_H_vals = naive_stats['H_vals']
        prev_cd_H_vals = cd_stats['H_vals']

        # Record snapshots and parameters every 10 steps
        record_snapshots(snapshots, k, q_naive, q_cd, lam_k, use_weights, log_weights_naive, log_weights_cd, 
                        resampling_count_naive, resampling_count_cd, param_history, A_ansatz)

        # Randomize momenta for naive HMC every momentum_refresh_interval steps
        # if (k % momentum_refresh_interval == 0) and (k < N_steps):
        #     key, sub = jax.random.split(key)

        #     p_naive = jax.random.normal(sub, (M, dim))
        #     p_cd = p_naive.copy()

        
        

        if k == N_steps:
            break

        lam_k1 = float(lam_fn(t_k + delta_t))
        dot_lam_k1 = float(dot_lam_fn(t_k + delta_t))

        # Check next lambda values for NaNs
        if jnp.isnan(lam_k1):
            print(f"⚠️  NaN detected in lam_k1 at step {k}")
            break
        if jnp.isnan(dot_lam_k1):
            print(f"⚠️  NaN detected in dot_lam_k1 at step {k}")
            break

        key, sub = jax.random.split(key)
        subs = jax.random.split(sub, M)
        

        # --- Naïve step ---
        # q_naive, p_naive = jax.jit(naive_step)(q_naive, p_naive, lam_k, lam_k1, eps, eps*momentum_refresh_interval, subs)

        # # Check for NaNs in naive HMC
        # if check_nans("q_naive", q_naive, k):
        #     print(f"  Stopping simulation due to NaNs in naive HMC at step {k}")
        #     break
        # if check_nans("p_naive", p_naive, k):
        #     print(f"  Stopping simulation due to NaNs in naive HMC at step {k}")
        #     break

        # --- Compute importance weights for naive HMC SMC ---
        log_weight_update = compute_naive_weights(q_naive, p_naive, lam_k, lam_k1, make_T, make_V)
        
        if use_weights:
            # Apply weight update
            log_weights_naive = log_weights_naive + log_weight_update
            
            # Check for NaNs in weights
            if check_nans("log_weights_naive", log_weights_naive, k):
                print(f"  Stopping simulation due to NaNs in naive weights at step {k}")
                break
            
            # Check if resampling is needed for naive HMC
            ess = compute_ess(log_weights_naive)
            ess_ratio = ess / M
            
            if ess_ratio < ess_threshold:
                print(f"  Resampling naive HMC at step {k}: ESS = {ess:.1f}/{M} ({ess_ratio:.3f})")
                key, sub = jax.random.split(key)
                q_naive, p_naive, log_weights_naive = multinomial_resample(q_naive, p_naive, log_weights_naive, sub, M)
                resampling_count_naive += 1
                print(f"    Naive HMC resampling completed. Total resampling events: {resampling_count_naive}")
        else:
            # Keep weights at 1 (log_weights = 0) when not using weights
            # NO RESAMPLING when use_weights=False
            log_weights_naive = jnp.zeros(M)

        # --- CD step ---
        try:
            L = eps*momentum_refresh_interval
            key, sub = jax.random.split(key)
            subs = jax.random.split(sub, M)
            cd_step = jax.vmap(lambda q, p, lam, lam_next, dot_lam, dot_lam_next, eps, rng_key: with_maruyama(make_cd_leapfrog_step(make_T(lam), make_V(lam), A_ansatz, lam, lam_next, dot_lam, dot_lam_next))(q=q, p=p, eps=eps, L=L, rng_key=rng_key), in_axes=(0, 0, None, None, None, None, None, 0))
            q_cd, p_cd = jax.jit(cd_step)(q_cd, p_cd, lam_k, lam_k1, dot_lam_k, dot_lam_k1, eps, subs)

            # --- Compute counterdiabatic work for CD-HMC weights ---
            if use_weights:
                try:
                    # Compute the differential work for counterdiabatic driving
                    work_vals = compute_counterdiabatic_work(q=q_cd, p=p_cd, lam_k=lam_k, lam_k1=lam_k1, A_ansatz=A_ansatz, make_T=make_T, make_V=make_V)
                    
                    # Integrate work over the time step (multiply by delta_t)
                    # The weight update is exp(-W) where W is the integrated work
                    work_integral = work_vals * delta_t
                    log_weight_update_cd = work_integral  # exp(W) = exp(∫dW)
                    
                    # Apply weight update
                    log_weights_cd = log_weights_cd + log_weight_update_cd
                    
                    # Check for NaNs in CD weights
                    if check_nans("log_weights_cd", log_weights_cd, k):
                        print(f"  Stopping simulation due to NaNs in CD weights at step {k}")
                        break
                    
                    # Check if resampling is needed for CD-HMC
                    ess_cd = compute_ess(log_weights_cd)
                    ess_ratio_cd = ess_cd / M
                    
                    if ess_ratio_cd < ess_threshold:
                        print(f"  Resampling CD-HMC at step {k}: ESS = {ess_cd:.1f}/{M} ({ess_ratio_cd:.3f})")
                        key, sub = jax.random.split(key)
                        q_cd, p_cd, log_weights_cd = multinomial_resample(q_cd, p_cd, log_weights_cd, sub, M)
                        resampling_count_cd += 1
                        print(f"    CD-HMC resampling completed. Total resampling events: {resampling_count_cd}")
                        
                except Exception as e:
                    print(f"⚠️  Error computing counterdiabatic work at step {k}: {e}")
                    # Continue with zero weights if work computation fails
                    log_weights_cd = jnp.zeros(M)
            else:
                # NO RESAMPLING when use_weights=False
                # Keep weights at 1 (log_weights = 0) when not using weights
                log_weights_cd = jnp.zeros(M)

            # if k % 10 == 0 and k > 0:
            #         key, sub = jax.random.split(key)
            #         p_cd = jax.random.normal(sub, (M, dim))
            
            # Check for NaNs in CD HMC
            if check_nans("q_cd", q_cd, k):
                print(f"  Stopping simulation due to NaNs in CD HMC at step {k}")
                # Debug: check ansatz values for the problematic samples
                if not isinstance(A_ansatz, AnalyticAnsatz):
                    print(f"  Debugging ansatz values at step {k}:")
                    # Check a few samples for ansatz values
                    for i in range(min(5, len(q_cd))):
                        try:
                            ansatz_val = A_ansatz(q_cd[i], p_cd[i])
                            print(f"    Sample {i}: q={q_cd[i]}, p={p_cd[i]}, A={ansatz_val}")
                        except:
                            print(f"    Sample {i}: Error computing ansatz value")
                break
            if check_nans("p_cd", p_cd, k):
                print(f"  Stopping simulation due to NaNs in CD HMC at step {k}")
                break
                
        except Exception as e:
            print(f"⚠️  Error in CD step at step {k}: {e}")
            break

        # --- Re-equilibration steps after CD step ---
        if re_equil_steps > 0:
            # Store pre-equilibration state

            naive_step = jax.vmap(lambda q, p, lam, lam_next, eps, L, rng_key: with_maruyama(make_leapfrog_step(make_T(lam), make_V(lam)))(q,p,eps,L=L, rng_key=rng_key), in_axes=(0, 0, None, None, None, None, 0))

            q_cd_pre_equil = q_cd.copy()
            p_cd_pre_equil = p_cd.copy()
            
            # Perform re-equilibration using naive HMC steps at the CURRENT lambda value
            # T_current = make_T(lam_k1)  # Use the next lambda value
            # V_current = make_V(lam_k1)
            # equil_step = with_maruyama(make_leapfrog_step(T_current, V_current))
            
            for equil_idx in range(re_equil_steps):
                key, sub = jax.random.split(key)
                subs = jax.random.split(sub, M)
                equil_eps = 0.05
                equil_L = 4.0 # eps*momentum_refresh_interval
                # q_cd_pre_equil, p_cd_pre_equil = generate_initial_samples(M, make_T, make_V, lam_k1, sub, dim, num_steps=1000, eps=0.1, L=4.0)
                q_cd_pre_equil, p_cd_pre_equil = jax.jit(naive_step)(q_cd_pre_equil, p_cd_pre_equil, lam_k1, None, equil_eps, equil_L, subs)
                # q_cd_pre_equil, p_cd_pre_equil = jax.vmap(lambda q, p: equil_step(q, p, eps/10, L=eps*momentum_refresh_interval, rng_key=sub))(q_cd_pre_equil, p_cd_pre_equil)

                # q_cd_pre_equil = q_cd_pre_equil
                # p_cd_pre_equil = p_cd_pre_equil

                
                # Check for NaNs during re-equilibration
                if check_nans("re_equil_q", q_cd_pre_equil, f"{k}_{equil_idx}"):
                    print(f"  Stopping re-equilibration due to NaNs at step {k}, equil {equil_idx}")
                    break
                if check_nans("re_equil_p", p_cd_pre_equil, f"{k}_{equil_idx}"):
                    print(f"  Stopping re-equilibration due to NaNs at step {k}, equil {equil_idx}")
                    break
                
                # Randomize momenta periodically during re-equilibration
                # if equil_idx % 10 == 0 and equil_idx > 0:
                #     key, sub = jax.random.split(key)
                #     p_cd_pre_equil = jax.random.normal(sub, (M, dim))
            
            
            
            # Store post-equilibration state at the current snapshot time
            # This represents the state after CD step + re-equilibration at the current lambda
            if k % 10 == 0:  # Store at the current snapshot time
                snapshots['cd_post_equil'].append(np.array(q_cd_pre_equil))
                snapshots['lam_post_equil'].append(lam_k1) # Store lambda at post-equilibration (use lam_k1 since re-equilibration happens at next lambda)

            q_cd = q_cd_pre_equil.copy()
            p_cd = p_cd_pre_equil.copy()
        else:
            # When re_equil_steps = 0, store the CD state directly as post-equilibration
            if k % 10 == 0:  # Store at the current snapshot time
                snapshots['cd_post_equil'].append(np.array(q_cd))
                snapshots['lam_post_equil'].append(lam_k)
    
    # Ensure the final state is captured in post-equilibration snapshots
    # This is especially important when re_equil_steps = 0
    if len(snapshots['cd_post_equil']) == 0 or (k % 10 != 0):
        # If no post-equilibration snapshots exist or the last step wasn't captured
        snapshots['cd_post_equil'].append(np.array(q_cd))
        snapshots['lam_post_equil'].append(lam_k)

    # Add the detailed energy statistics to snapshots
    snapshots['detailed_energy_stats'] = all_energy_stats
    snapshots['detailed_times'] = all_times

    print(f"Simulation completed after {k} steps")
    if re_equil_steps > 0:
        print(f"Performed {re_equil_steps} re-equilibration steps after each CD step")
    if use_weights:
        print(f"Total resampling events - Naive HMC: {resampling_count_naive}, CD-HMC: {resampling_count_cd}")
    
    return A_ansatz, snapshots, loss_histories, param_history 